version: '3.8'

services:
  legal-document-api:
    build: .
    container_name: legal-document-intelligence
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=false
      - MAX_FILE_SIZE=50000000
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./models:/app/models
      - ./output:/app/output
      - ./logs:/app/logs
    restart: unless-stopped
    mem_limit: 4g
    cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  # CLI mode for batch processing (optional)
  legal-document-cli:
    build: .
    container_name: legal-document-cli
    volumes:
      - ./Collections:/app/Collections
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
    restart: "no"
    mem_limit: 4g
    cpus: '2.0'
    profiles:
      - cli
